---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: 2.5.8
      sourceRef:
        kind: HelmRepository
        name: pihole-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: pihole/pihole
      tag: "2022.02.1"
    serviceWeb:
      loadBalancerIP: "192.168.0.55"
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    serviceDns:
      loadBalancerIP: "192.168.0.55"
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    persistentVolumeClaim:
      enabled: true
      existingClaim: pihole-config
