---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: 2.5.8
      sourceRef:
        kind: HelmRepository
        name: pihole-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: pihole/pihole
      tag: "2022.02.1"
    serviceWeb:
      loadBalancerIP: "192.168.0.55"
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    serviceDns:
      loadBalancerIP: "192.168.0.55"
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    dnsmasq:
      # these won't actually show up in the PiHole gui, but they should be added to the dnsmasq config
      customDnsEntries:
        - address=/traefik.neilfrench.me/192.168.0.50
        - address=/pihole.neilfrench.me/192.168.0.50
        - address=/longhorn.neilfrench.me/192.168.0.50
        - address=/k8s1/192.168.0.220
        - address=/k8s2/192.168.0.194
        - address=/k8s3/192.168.0.110
        - address=/k8s4/192.168.0.186
    persistentVolumeClaim:
      enabled: true
      existingClaim: pihole-config
    admin:
      existingSecret: "pihole-admin-secret"
      passwordKey: "pihole-admin-secret"
