apiVersion: v1
data:
    pihole-admin-secret: ENC[AES256_GCM,data:dAFHIOd0cobrq6EyUQ==,iv:RWxxUo+Zng3qtcdzcdECfsXzXcfMadL2w+6yshAABOk=,tag:4J5zFA25oYD8Vb91tCbPCw==,type:str]
kind: Secret
metadata:
    name: pihole-admin-secret
    namespace: networking
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fl92uj8fwujcphes4cxm82qlztxf4kh6j0d2a9at7alpml266p3sedrvx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydTIwM25VK3drSWFjdDN6
            WnpIVHRQdFNMVmVEMkR2djdOOUtYTHRobUNFCjAxOHVZdnJtNmphVDhuTVVMM0pM
            U0VJNWkxWDJJT3hJSVFhZUhRV0ZBdk0KLS0tIEVTSW5IdG82ZEhNdUVoM2pGUVNx
            SnFiWmkvWkg0ZFJFRHpOZURMN25UV00KPugQ5I+6BcHn7Vt92BEfqoDdvDGIGcJA
            ViRgL78bH3Z2Ki1jaceZYo67lDYWbuzn9I4l5BbVGDql6V9GmG4Aeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-12T22:21:22Z"
    mac: ENC[AES256_GCM,data:kzHu8ZcRCkliNWag35ZcbO1vCpaOCriOAm4QNa4Y0rEw1S+tcf0Dm3dPzV1sZynEJpTCqhN3hSe952F52SESylREnR1OYL722Go/vwzEhvSUqk4Lxgn/Znk7XnpaIl9/qHeU/CMwhATnhbhiep9VvPrwk0GoH4GK9YCZzdd26l0=,iv:QxnCZT+Djrt+lVGSGRBZ7Lx6JsykvcNN3w3Eq3oRY+M=,tag:c8mxiLox7l5a3GRT3Dn39A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
