---
apiVersion: v1
kind: Service
metadata:
  name: wyze-bridge
spec:
  selector:
    app: wyze-bridge
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: http
