# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:VkIrDqyJ9L3HPufASHnxb0chjGxZGv+Mi3Wov8OlBfCAvJCbJA==,iv:lpIStPlWeQFhbsjvro4yryZbBigzkgjofJeI9yfIREY=,tag:aDRxAkoy1m0GfF7FrVZENg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fl92uj8fwujcphes4cxm82qlztxf4kh6j0d2a9at7alpml266p3sedrvx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTN09aaG9HckloREVyeWo0
            dFZGTi93MmRlTFhIaS9Vd2xzdHRocFE5Q0JRCmVKSnBkbGtVaEFXQnNQdFpLWi9h
            aXpvT2xVZWpLeVM3d3NxSXFVS0FmUUEKLS0tIGdyVXJieXhYN2U0dU1mbEFXWmgy
            V1JPZHZyT1BKWnRER2RhYnpncUVhcDAKmCiHtDRnB6Y5jmngKSvImyDaotVPE3oW
            y5JL8Dk6cJB9kc6b6LXyCLI73w1N1FgJYXkRhpKILufBS1I7iA/F3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-09T17:47:23Z"
    mac: ENC[AES256_GCM,data:NfQES3nS+dpR1ebLNmhr2aeXif6VV1RCXvnIHloaKLso34Zb662NbgQwhMDogGoUeB6Ihrren1L4ThDwZAr/9eCQGXBeprR4w7PWmZkGpdyt2bmr4Wq2JiOXAogG70aebRN9EXvBGK27PWrF08JyNu2ujs7ScblqtT7Y209h+i8=,iv:VISf93MhHGu2DaV83KLWxsaKfj+4F2zhYOJE+cFLzFk=,tag:Jlbxz9eVIBOpFEMzWcRBcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
